const express = require("express");
const cors = require("cors");
const {
  Client,
  GatewayIntentBits,
  Partials,
  WebhookClient
} = require("discord.js");

const app = express();
const PORT = Number(process.env.PORT || 10000);

const DISCORD_TOKEN = process.env.DISCORD_TOKEN;
const GUILD_ID = process.env.DISCORD_GUILD_ID;
const REPORT_WEBHOOK_URL = process.env.REPORT_WEBHOOK_URL || "";

if (!DISCORD_TOKEN) {
  console.error("❌ Missing DISCORD_TOKEN environment variable.");
  process.exit(1);
}

if (!GUILD_ID) {
  console.error("❌ Missing DISCORD_GUILD_ID environment variable.");
  process.exit(1);
}

app.use(cors());
app.use(express.json({ limit: "1mb" }));

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildPresences
  ],
  partials: [Partials.GuildMember, Partials.User]
});

let latestWelcome = null;
let botReady = false;
let lastMemberSnapshot = [];
let lastSnapshotAt = 0;
let snapshotPromise = null;

function cleanText(value, max = 2000) {
  return String(value ?? "").trim().slice(0, max);
}

function getDisplayName(member) {
  return (
    member.displayName ||
    member.user.globalName ||
    member.user.username ||
    "Unknown Member"
  );
}

function getStatus(member) {
  // Depruuu Core rule:
  // ONLY Discord "online" is shown as Online.
  // idle / dnd / offline / missing presence => Offline.
  return member.presence?.status === "online" ? "online" : "offline";
}

function memberNumberMap(members) {
  // Member number is generated by server join order.
  // Oldest joined member = #00001.
  // Same join time is resolved by Discord ID for deterministic ordering.
  const sorted = [...members].sort((a, b) => {
    const aTime = a.joinedTimestamp || Number.MAX_SAFE_INTEGER;
    const bTime = b.joinedTimestamp || Number.MAX_SAFE_INTEGER;

    if (aTime !== bTime) return aTime - bTime;
    return BigInt(a.id) < BigInt(b.id) ? -1 : 1;
  });

  const map = new Map();
  sorted.forEach((member, index) => {
    map.set(member.id, index + 1);
  });

  return map;
}

function serializeMember(member, number) {
  return {
    id: member.id,
    discordId: member.id,
    displayName: getDisplayName(member),
    username: member.user.username,
    globalName: member.user.globalName || null,
    avatar: member.user.displayAvatarURL({
      extension: "png",
      size: 256,
      forceStatic: false
    }),
    status: getStatus(member),
    joinedAt: member.joinedAt ? member.joinedAt.toISOString() : null,
    memberNumber: number,
    memberNumberFormatted: `#${String(number).padStart(5, "0")}`
  };
}

async function getGuildMembers() {
  const guild = await client.guilds.fetch(GUILD_ID);

  // Fetch all guild members so the API can show the complete member list.
  await guild.members.fetch();

  const members = [...guild.members.cache.values()];
  const numbers = memberNumberMap(members);

  return members
    .map(member => serializeMember(member, numbers.get(member.id)))
    .sort((a, b) => a.memberNumber - b.memberNumber);
}

async function getCachedMembers() {
  const now = Date.now();

  // Avoid hammering Discord when several frontend requests arrive together.
  if (lastMemberSnapshot.length && now - lastSnapshotAt < 8000) {
    return lastMemberSnapshot;
  }

  if (snapshotPromise) return snapshotPromise;

  snapshotPromise = getGuildMembers()
    .then(members => {
      lastMemberSnapshot = members;
      lastSnapshotAt = Date.now();
      return members;
    })
    .finally(() => {
      snapshotPromise = null;
    });

  return snapshotPromise;
}

app.get("/", (req, res) => {
  res.json({
    ok: true,
    name: "Depruuu Core API",
    status: botReady ? "online" : "starting",
    endpoints: [
      "GET /api/health",
      "GET /api/stats",
      "GET /api/members",
      "GET /api/members/:id",
      "GET /api/welcome",
      "POST /api/report"
    ]
  });
});

app.get("/api/health", (req, res) => {
  res.json({
    ok: true,
    api: "online",
    discordBot: botReady ? "online" : "starting",
    guildConfigured: Boolean(GUILD_ID),
    timestamp: new Date().toISOString()
  });
});

app.get("/api/stats", async (req, res) => {
  try {
    const members = await getCachedMembers();

    res.json({
      ok: true,
      total: members.length,
      online: members.filter(m => m.status === "online").length,
      offline: members.filter(m => m.status === "offline").length,
      updatedAt: new Date().toISOString()
    });
  } catch (error) {
    console.error("GET /api/stats:", error);
    res.status(503).json({
      ok: false,
      error: "Discord member data is temporarily unavailable."
    });
  }
});

app.get("/api/members", async (req, res) => {
  try {
    const members = await getCachedMembers();

    res.json({
      ok: true,
      members,
      count: members.length,
      updatedAt: new Date().toISOString()
    });
  } catch (error) {
    console.error("GET /api/members:", error);
    res.status(503).json({
      ok: false,
      error: "Discord member data is temporarily unavailable."
    });
  }
});

app.get("/api/members/:id", async (req, res) => {
  try {
    const members = await getCachedMembers();
    const member = members.find(m => m.id === req.params.id);

    if (!member) {
      return res.status(404).json({
        ok: false,
        error: "Member not found."
      });
    }

    res.json({
      ok: true,
      member
    });
  } catch (error) {
    console.error("GET /api/members/:id:", error);
    res.status(503).json({
      ok: false,
      error: "Discord member data is temporarily unavailable."
    });
  }
});

app.get("/api/welcome", (req, res) => {
  if (!latestWelcome) {
    return res.json({
      ok: true,
      hasNewMember: false,
      member: null
    });
  }

  res.json({
    ok: true,
    hasNewMember: true,
    member: latestWelcome
  });
});

app.post("/api/report", async (req, res) => {
  try {
    if (!REPORT_WEBHOOK_URL) {
      return res.status(503).json({
        ok: false,
        error: "Report system is not configured on the server."
      });
    }

    const {
      communityName,
      discordUsername,
      discordId,
      category,
      reportedMember,
      description,
      evidenceLink,
      date,
      additionalInformation
    } = req.body || {};

    if (!category || !description) {
      return res.status(400).json({
        ok: false,
        error: "Category and description are required."
      });
    }

    const webhook = new WebhookClient({ url: REPORT_WEBHOOK_URL });

    await webhook.send({
      username: "Depruuu Core Reports",
      embeds: [
        {
          title: "NEW COMMUNITY REPORT",
          color: 0x9b7edc,
          fields: [
            { name: "Community Name", value: cleanText(communityName || "-"), inline: true },
            { name: "Reporter", value: cleanText(discordUsername || "-"), inline: true },
            { name: "Discord Username", value: cleanText(discordUsername || "-"), inline: true },
            { name: "Discord ID", value: cleanText(discordId || "-"), inline: true },
            { name: "Category", value: cleanText(category), inline: true },
            { name: "Reported Member", value: cleanText(reportedMember || "-"), inline: true },
            { name: "Date", value: cleanText(date || "-"), inline: true },
            { name: "Evidence", value: cleanText(evidenceLink || "-"), inline: false },
            { name: "Description", value: cleanText(description), inline: false },
            { name: "Additional Information", value: cleanText(additionalInformation || "-"), inline: false }
          ],
          timestamp: new Date().toISOString(),
          footer: { text: "Depruuu Core • Community Report System" }
        }
      ]
    });

    return res.json({
      ok: true,
      message: "Report sent successfully."
    });
  } catch (error) {
    console.error("POST /api/report:", error);
    return res.status(500).json({
      ok: false,
      error: "Could not send the report."
    });
  }
});

client.on("ready", async () => {
  botReady = true;
  console.log(`✅ Discord bot logged in as ${client.user.tag}`);

  try {
    const guild = await client.guilds.fetch(GUILD_ID);
    console.log(`✅ Connected to server: ${guild.name} (${guild.id})`);
    await getCachedMembers();
    console.log(`✅ Member cache loaded: ${lastMemberSnapshot.length} members`);
  } catch (error) {
    console.error("❌ Could not load Discord server members:", error);
  }
});

client.on("guildMemberAdd", async member => {
  if (member.guild.id !== GUILD_ID) return;

  try {
    const members = await getGuildMembers();
    lastMemberSnapshot = members;
    lastSnapshotAt = Date.now();

    const found = members.find(m => m.id === member.id);

    latestWelcome = {
      ...(found || serializeMember(member, members.length)),
      welcomedAt: new Date().toISOString()
    };

    console.log(`🎉 New member joined: ${getDisplayName(member)} (${member.id})`);
  } catch (error) {
    console.error("guildMemberAdd:", error);
  }
});

client.on("guildMemberRemove", async member => {
  if (member.guild.id !== GUILD_ID) return;

  // Refresh the snapshot after a member leaves.
  lastMemberSnapshot = [];
  lastSnapshotAt = 0;
  console.log(`👋 Member left: ${member.user?.tag || member.id}`);
});

client.on("error", error => {
  console.error("Discord client error:", error);
});

process.on("unhandledRejection", error => {
  console.error("Unhandled rejection:", error);
});

app.listen(PORT, () => {
  console.log(`🌸 Depruuu Core API running on port ${PORT}`);
});

client.login(DISCORD_TOKEN);
